app:
  server:
    host: localhost
    port: 8080
    admin:
      email: admin@gmail.com
      password: 123456

database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: togo
  timezone: Asia/Ho_Chi_Minh